'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:55009/")>  _
        Public ReadOnly Property baseURL() As String
            Get
                Return CType(Me("baseURL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://arcgis:6080/arcgis/rest/services/GIS/2010_Imagery/MapServer")>  _
        Public ReadOnly Property baseMapURL() As String
            Get
                Return CType(Me("baseMapURL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://schmidt:6080/arcgis/rest/services/Cemetery_Config_Test/MapServer")> _
        Public ReadOnly Property cemeteryMapURL() As String
            Get
                Return CType(Me("cemeteryMapURL"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://schmidt:6080/arcgis/rest/services/Cemetery_Config_Test/MapServer/0/query")> _
        Public ReadOnly Property cemeteries() As String
            Get
                Return CType(Me("cemeteries"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://schmidt:6080/arcgis/rest/services/Cemetery_Config_Test/MapServer/1/query")> _
        Public ReadOnly Property divisions() As String
            Get
                Return CType(Me("divisions"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://schmidt:6080/arcgis/rest/services/Cemetery_Config_Test/MapServer/2/query")> _
        Public ReadOnly Property blocks() As String
            Get
                Return CType(Me("blocks"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://schmidt:6080/arcgis/rest/services/Cemetery_Config_Test/MapServer/3/query")> _
        Public ReadOnly Property lots() As String
            Get
                Return CType(Me("lots"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://schmidt:6080/arcgis/rest/services/Cemetery_Config_Test/MapServer/5/query")> _
        Public ReadOnly Property spaces() As String
            Get
                Return CType(Me("spaces"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://schmidt:6080/arcgis/rest/services/Cemetery_Config_Test/FeatureServer/4")> _
        Public ReadOnly Property burials() As String
            Get
                Return CType(Me("burials"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("EMAIL_SERVER(eg mail.winfieldks.org)")> _
        Public ReadOnly Property SMTPClient() As String
            Get
                Return CType(Me("SMTPClient"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("CEMETERY_SYSTEM_EMAIL_ADDRESS")> _
        Public ReadOnly Property SMTPUserName() As String
            Get
                Return CType(Me("SMTPUserName"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("CEMETERY_SYSTEM_EMAIL_ADDRESS_PASSWORD")> _
        Public ReadOnly Property SMTPPassword() As String
            Get
                Return CType(Me("SMTPPassword"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("http://schmidt:6080/arcgis/rest/services/Cemetery_Config_Test/FeatureServer/5/")> _
        Public ReadOnly Property SpacesFeatureService() As String
            Get
                Return CType(Me("SpacesFeatureService"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("City of Winfield")> _
        Public ReadOnly Property OrganizationName() As String
            Get
                Return CType(Me("OrganizationName"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Winfield")> _
        Public ReadOnly Property OrganizationName_Short() As String
            Get
                Return CType(Me("OrganizationName_Short"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Kansas")> _
        Public ReadOnly Property State() As String
            Get
                Return CType(Me("State"), String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.wincem.My.MySettings
            Get
                Return Global.wincem.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
